### ISSUE TITLE
[Bug] App crashes when opening a video

### ISSUE THREAD

**Issue by backstab5983** [Balackburn/YTLitePlus#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.3.1
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): [v19.07.4-2.6.1](https://github.com/Balackburn/YTLitePlus/releases/tag/v19.07.4-2.6.1)

### Describe the bug

The app opens fine for me, can navigate the menus, etc. differently than https://github.com/Balackburn/YTLitePlus/issues/80

Shorts also work fine, but clicking on any video makes the app crash.

### Steps to reproduce the issue

1. Open app
2. Try to play any "long form" video
3. Crash

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
You are right I am removing the release for now, didn’t even tested it myself 🤦

Please use the 19.06.2-2.6 for now I will do some investigation later today when I am home.

**Comment by degen91** [comment]
Might be this: https://github.com/Galactic-Dev/iSponsorBlock/pull/107

**Comment by Balackburn** [comment]
Fixed on 19.08.2-2.7

**Comment by jaconri91** [comment]
> Fixed on 19.08.2-2.7

I know this issue is now closed, but I am still experiencing the same issue documented above. I am using the latest version.

**Comment by degen91** [comment]
I do as well, and also on uYou+. Though the issue was said to be fixed in an iSponserBlock update, I still experienced crashes on video start and disabling iSponserBlock eliminated those crashes on YTLitePlus and uYou+.
